In [1]:
import plotly.io as pio
pio.renderers.default = "notebook"
from yfinance_api3.classes.stock_client import StockClient
from yfinance_api3.classes.quant_analytics import QuantAnalytics as qa
import yfinance_api3.modules.plots as plots

In [8]:
client = StockClient(ttl_price=60, ttl_info=900)
quant = qa(client)
symbols = ["AAPL", "MSFT", "NVDA", "GOOGL"]
mag7 = ["AAPL", "MSFT", "NVDA", "GOOGL", "META", "AMZN", "TSLA"]

In [10]:
quant.stock_report (symbol='AAPL', benchmark = 'SPY', period= '20y', risk_free_rate= 0.01)

{'symbol': 'AAPL',
 'period': '20y',
 'annualised_volatility': 0.31435266685390034,
 'max_drawdown': -0.6086671726908148,
 'sharpe_ratio': 0.9105734701669299,
 'sortino_ratio': 1.26031546208998,
 'beta': 1.0650700380436116,
 'calmar_ratio': 0.45938226764146933,
 'var_95_1d': np.float64(0.029406843027027407),
 'cvar_95_1d': 0.044937421341886}

In [15]:
quant.metrics_df (symbols=symbols, benchmark = 'SPY', period = '1y', risk_free_rate = 0.01)

                           AAPL      MSFT      NVDA     GOOGL
annualised_volatility  0.232934  0.246642  0.333032  0.282554
max_drawdown          -0.137985 -0.339101 -0.202144 -0.203665
sharpe_ratio           1.221510  0.443899  2.037124  2.795462
sortino_ratio          1.923325  0.551615  3.325532  4.880407
beta                   1.005953  0.955707  1.774766  1.189709
calmar_ratio           2.221460  0.272212  4.359722  5.598800
var_95_1d              0.021379  0.023499  0.033054  0.023170
cvar_95_1d             0.030812  0.035383  0.040536  0.031772

In [11]:
quant.sortino_ratio (symbol='AAPL', period = '20y', risk_free_rate = 0.01, interval = '1d')

1.26031546208998

In [12]:
quant.sharpe_ratio (symbol='AAPL', period = '20y', risk_free_rate = 0.01, interval = '1d')

0.9105734701669299

In [13]:
quant.rolling_sharpe_df (symbols=symbols, period= '1y', window = 63, risk_free_rate = 0.01, interval= '1d')

                AAPL      MSFT      NVDA     GOOGL
date
2025-07-28  0.483071  5.653173  6.315060  2.585421
2025-07-29  0.185315  5.698629  6.580894  2.934235
2025-07-30 -0.083360  5.572937  6.809309  3.033477
2025-07-31 -0.309866  5.945210  6.690778  2.778263
2025-08-01 -0.788630  5.582219  5.959913  2.347763
...              ...       ...       ...       ...
2026-04-20  1.117625 -0.918666  1.030287  0.425866
2026-04-21  1.282702 -0.617161  1.423861  0.557434
2026-04-22  1.601669 -0.118972  1.255931  0.575615
2026-04-23  1.573122 -0.739066  1.003572  0.465370
2026-04-24  1.455830 -0.877129  1.282456  0.802895

[188 rows x 4 columns]

In [14]:
quant.portfolio_sharpe (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y', risk_free_rate = 0.01)

2.2994309487872058

In [16]:
quant.calmar_ratio (symbol= 'AAPL', period= '3y')

0.5677109789661625

In [26]:
metrics=plots.list_metrics()
metrics

['sharpe',
 'sortino',
 'calmar',
 'volatility',
 'max_drawdown',
 'var',
 'cvar',
 'beta']

In [33]:
for m in metrics:
    fig=plots.scatter(quant,symbols,metric=m, period_x='2y', period_y='5y', benchmark= 'SPY', risk_free_rate= 0.01)
    fig.show()